deleteTweetを実装しました。
tk-Hofman/twitter-clone pull request #27
Opened 2022-05-04 01:52 UTC by tk-Hofman

deleteTweetを実装しました。

deleteTweet.tsファイルにdeleteTweetという関数を作成して引数にidを受け取るようにしています。
作成したデータの中に受け取った引数と同じidのデータがあればそのデータを削除します。
もしなければnullを返すようにしました。

deleteTweet.test.tsファイルで引数を渡し、テストしたところ成功しました。

addTweetファイルが少し修正箇所が必要でしたので只今変更作業中です

2022-05-06 14:59 UTC, ts020 requested changes

2022-05-06 14:59 UTC, ts020 commented on server/src/infr/addTweet.ts
> +      const resultMap = map[String(Object.keys(map).length + 1)] = {
コレは１回変数に格納した方がわかりやすくなる
```
const  id = String(Object.keys(map).length + 1)
```

2022-05-06 14:59 UTC, ts020 commented on server/src/infr/deleteTweet.ts
>  export async function deleteTweet(id: string): Promise<Record<string, TweetDataObj> | null> {
ココは返り値voidでいいので`Promise<void>`を返り値の型にすると良い

2022-05-06 14:59 UTC, ts020 commented on server/src/infr/addTweet.ts
> +        //createdAt: date.toLocaleString(),
createdAtも追加しとこう

2022-05-06 14:59 UTC, ts020 commented on server/src/infr/getTweet.test.ts
>  })
下記のテストを追加してください
- addTweetしたtweetをgetTweetで取得する
- deleteTweetしてgetTweetでnullが帰ってくる

2022-05-06 20:11 UTC, tk-Hofman commented on server/src/infr/deleteTweet.ts
>  export async function deleteTweet(id: string): Promise<Record<string, TweetDataObj> | null> {
deleteTweetしてgetTweetでnullが帰ってくる

と書いてあるのでe<void | null>でいいでしょうか？
問題なく削除できた場合は何も返さないと言うことでよろしいですか？

2022-05-06 22:30 UTC, tk-Hofman commented
addTweetしたtweetをgetTweetで取得する
deleteTweetしてgetTweetでnullが帰ってくる

⇧こちらのテストなんですが今のところ

getTweet, deleteTweet,addTweet,getAllTweet 、全てのファイルで
以下のようなデータを作っているため、全てのファイルに別々のデータがある形になっています。

const map: Record<string, TweetDataObj> = {
  1: {
    id: "1",
    message: "hello",
    like: 0,
    createdAt: date.toLocaleString(),
    userId: "tokitoki"
  },
  2: {
    id: "2",
    message: "world",
    like: 0,
    createdAt: date.toLocaleString(),
    userId: "tokitoki"
  },
  3: {
    id: "3",
    message: "japan",
    like: 0,
    createdAt: date.toLocaleString(),
    userId: "tokitoki"
  }
}


なのでaddTweetしてもaddTweetファイル内のデータに追加されるのでgetTweetファイルのデータには追加されないようになっています。　deleteTweetも同じです。

なのでtweetDataというファイル作成してデータを一つにしてみます。

2022-05-06 22:53 UTC, tk-Hofman commented
今まではdeletTweet, getTweet, getTweetAll, addTweet　全てのファイルにデータを作成していたので
addTweetでtweetを増やしてもaddTweetファイルのデータに追加されるだけで、getTweetのファイルのデータには追加
されません。　deleteTweetも同じです。

なのでこちらのtestができませんでした。

addTweetしたtweetをgetTweetで取得する
deleteTweetしてgetTweetでnullが帰ってくる


そのため新しくtweetDataファイルを作成してデータを一つにしました。

2022-05-07 01:29 UTC, tk-Hofman commented
質問した問題は全て解決できました。

2022-05-07 05:57 UTC, ts020 commented on server/src/infr/deleteTweet.ts
>  export async function deleteTweet(id: string): Promise<Record<string, TweetDataObj> | null> {
getTweetの実行結果がnullという話なので、deleteTweetの返り値への言及はないです。

因みに、deleteTweetの返り値がvoidとnullとするいう事は、nullが返ってくる時と返ってこない時でなにか意味が変わってくるということ？

2022-05-07 06:24 UTC, ts020 requested changes

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/addTweet.test.ts
>  type DataType = {
この型不要

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/addTweet.test.ts
> +    const idAndMessage: DataType =  await addTweet("yoshino","こんにちは")
ココの型宣言不要。

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/addTweet.ts
> +import map = require("./tweetData");
typescriptの場合、requireはなるべく書かない方が良い。
`import map from './tweetData'`とすべき

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/addTweet.ts
> +      const resultMap = map[String(Object.keys(map).length + 1)] = {
この処理がidに置き換わって無い
const resultMap = map[String(Object.keys(map).length + 1)]

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/deleteTweet.test.ts
> +    expect(removeData).toEqual(null)
deleteTweetの返り値が意外あり得なくて、全く動作検証になっていないので
ちゃんとデータが消せている事を確認する為に、getTweetを使って検証してください
```
await deleteTweet("1")
const result = await getTweet("1")
expect(result).toEqual(null)
```

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/deleteTweet.test.ts
> +    const removeData = await deleteTweet("2")
ココもdeleteTweetの返り値でテストするのやめる

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/deleteTweet.test.ts
> +    const removeData = await deleteTweet("aaaa")
ココもdeleteTweetの返り値でテストするのやめる

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/getTweet.test.ts
> +import map = require("./tweetData");
requireやめる

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/getTweet.test.ts
>  type TweetData = {
この型宣言不要

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/getTweet.ts
> +import map = require("./tweetData");
require使うのやめる

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/getTweet.ts
>  type TweetDataObj = {
不要

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/getTweetAll.test.ts
>    test('ツイートを全件取得', async () => {
下記のtestを追加してください。
- 1件addした後getAllしたケース
- 1件updateした後getAllしたケース
- 1件deleteした後getAllしたケース

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/putTweet.ts
> +    return Promise.resolve(console.log("正しいidを入力してください"))
エラーをthrowする形にしてください。
参考
https://typescript-jp.gitbook.io/deep-dive/type-system/exceptions

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/putTweet.ts
> +export async function putTweet(id: string, message: string):Promise<TweetDataObj | void> {
voidは実行しないって言う意味でなんでもありになってしまうので、返り値のunionTypeの一個として定義するのは辞めましょう。

利用側がいろんな関数でのvoidのケースを考えなくていけなくなります。
例えば、getTweetの返り値がvoidの時とaddTweetの返り値がvoidときなど、実装する関数によってvoidが意味する所が変わってくるので、極力何か返してあげた方が良い設計と言える

2022-05-07 06:24 UTC, ts020 commented on server/src/infr/putTweet.test.ts
> +    expect(put).toEqual(console.log("正しいidを入力してください"))
このテストは、マジでなんの意味も成していない。

2022-05-08 02:30 UTC, tk-Hofman commented on server/src/infr/putTweet.ts
> +  } catch (error: any) {
(error: any)　ここの型がわからなくてanyにしたのですが正確な型は存在しますか？

2022-05-09 11:39 UTC, tk-Hofman commented
server.jsも全てtypeScriptに変換しデータベースなしで書き直して行ってもいいでしょうか？

2022-05-12 13:13 UTC, ts020 requested changes

2022-05-12 13:13 UTC, ts020 commented on server/js/server.ts
> +import { getTweetAll } from "../src/infr/getTweetAll"
この辺を参考にして試してみて。
requireはtypescriptではつかない様にして！
https://wanago.io/2019/03/25/node-js-typescript-7-creating-a-server-and-receiving-requests/

2022-05-12 13:13 UTC, ts020 commented on server/package.json
> +  "type": "module",
これ、意味ないので取っちゃって

2022-05-12 13:13 UTC, ts020 commented on server/js/server.ts
> +import { getTweetAll } from "../src/infr/getTweetAll"
あと、jsディレクトに入れてるのミスだと思うので、srcに入れてください。
tsconfigに設定してあるの作業ディレクトリがsrc以下になってると思うのでその外側だと、typescriptの設定が適用されない

2022-05-12 13:15 UTC, ts020 commented on server/src/infr/putTweet.ts
> +  } catch (error: any) {
ここは、型を指定できないのでanyも書かなくてOK

2022-05-12 13:23 UTC, ts020 requested changes

2022-05-12 13:23 UTC, ts020 commented on server/src/infr/deleteTweet.ts
> +export async function deleteTweet(id: string): Promise<null> {
値を返す必要がないのでPromise<void>に変更してください

2022-05-12 13:23 UTC, ts020 commented on server/src/infr/deleteTweet.ts
> +  return Promise.resolve(null)
null入れなくて良い

2022-05-12 13:28 UTC, ts020 requested changes

2022-05-12 13:35 UTC, ts020 requested changes

2022-05-12 13:35 UTC, ts020 commented on server/src/infr/putTweet.ts
> +    for(let i = 0; 0 < Object.keys(map).length; i++) {
そもそも、ココでfor文を回す理由がない。
map[id]が見つからないと言うことは、指定IDのデータが存在しないと言うことなので素直に
```
throw new Error("idのデータが見つかりません");
```
とかけばOK

2022-05-12 13:38 UTC, ts020 commented on server/js/server.ts
> +import { getTweetAll } from "../src/infr/getTweetAll"
レビューがいつまで経っても終わらなくなるので、まずtestを全部書いて動かす事を完了させてください

2022-05-13 09:44 UTC, tk-Hofman commented on server/src/infr/deleteTweet.ts
> +export async function deleteTweet(id: string): Promise<null> {
deleteTweetをした際に存在しないidが送られてdelete出来なかった場合と、
存在するidが送られてきて、ちゃんとdeleteできた場合の返り値は、
別々の物を返した方がいいですか？

2022-05-13 09:46 UTC, tk-Hofman commented on server/src/infr/deleteTweet.ts
>  export async function deleteTweet(id: string): Promise<Record<string, TweetDataObj> | null> {
deleteTweetをした際に存在しないidが送られてきてdelete出来なかった場合と
ちゃんとdelete出来た場合で返す値を違う物にしようと思ってました。

2022-05-13 10:27 UTC, tk-Hofman commented on server/src/infr/putTweet.test.ts
> +    expect(putTweet('aaa', 'エラー出ると思う')).toEqual(new Error("idのデータが見つかりません"))
try catchを使用した場合のテストはどのようにすればいいでしょうか？

2022-05-13 12:45 UTC, tk-Hofman commented on server/src/infr/putTweet.test.ts
> +    catch(e: any) {
catch(e: any)ここは型指定しないとエラーが発生するのでanyでいいでしょうか？
catch(e: Error)でもエラーになりました。

2022-05-20 07:28 UTC, ts020 commented on server/src/infr/deleteTweet.test.ts
> +  test("2件目のツイートを削除", async () => {
idが見つからない場合のテストを追加してください

2022-05-20 07:30 UTC, ts020 commented on server/src/infr/deleteTweet.ts
> +  if(map[id]) {
idが見つからない場合にエラーを発行してください

2022-05-20 07:30 UTC, ts020 commented on server/src/infr/getTweet.test.ts
> +  test("addTweetで投稿した内容を取得", async () => {
これは、addTweet.test.tsで行う

2022-05-21 16:01 UTC, tk-Hofman commented on server/src/infr/deleteTweet.ts
>  export async function deleteTweet(id: string): Promise<Record<string, TweetDataObj> | null> {
この質問をした頃はうまくツイートが消せた場合はnullを返して、
削除できなかった場合はconsole.logでエラーメッセージのvoidを返そうと思っていました。

2022-05-22 23:01 UTC, tk-Hofman commented on server/src/infr/deleteTweet.ts
> +  return Promise.resolve(null)
@ts020 
ちゃんと削除できた場合は何も返さないと言うことでよろしいですか？

2022-05-22 23:03 UTC, tk-Hofman commented on server/src/infr/deleteTweet.ts
> +  if(map[id]) {
@ts020 
throw new Error("idのデータが見つかりません");
みたいな形でエラーを発行したのですが、testの方はtry catchを使用した方がいいですか？

2022-06-11 13:41 UTC, ts020 approved these changes
LGTM

2022-06-11 13:41 UTC, ts020 commented on server/src/infr/getTweetAll.test.ts
> +    expect(getAll).toEqual(map)
テストでは処理で使ってるデータとは別のデータで行うこと
理由は、処理がしくじっていてデータがバグっていても、比較対象が一緒なので正解となってしまって間違いを検出できなくなるため

2022-06-11 13:43 UTC, merged